name: Zh's Blog.
description: "个人博客"
meta_description: "笔记 代码 程序 网站"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://zh-blog.com"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
